spring.application.name=easyfinance
spring.output.ansi.enabled=ALWAYS

# Banco de dados SQLite configurado em EasyfinanceApplication
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


